[project]
name = "SecAware"
version = "0.0.0"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]
authors = [
    { name = "Alex Winder", email = "contact@alexwinder.com" }
]
dependencies = [
    "GitPython==3.1.46",
    "python-dotenv==1.2.2",
    "requests==2.32.5"
]

[build-system]
requires = ["hatchling==1.29.0"]
build-backend = "hatchling.build"