[project]
name = "SecAware"
version = "0.0.0"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]
authors = [
    { name = "Alex Winder", email = "contact@alexwinder.com" }
]
dependencies = [
    "python-dotenv~=1.2.0",
    "requests~=2.32.0"
]

[build-system]
requires = ["hatchling~=1.28.0"]
build-backend = "hatchling.build"