[project]
name = "SecAware"
version = "0.1.1"
classifiers = [
    "Development Status :: 3 - Alpha",
]
authors = [
    { name = "Alex Winder", email = "contact@alexwinder.com" }
]
dependencies = [
    "cvss==3.6",
    "dnspython==2.8.0",
    "GitPython==3.1.46",
    "python-dotenv==1.2.2",
    "requests==2.32.5",
    "semantic-version==2.10.0"
]
license = "GPL-3.0-only"

[build-system]
requires = ["hatchling==1.29.0"]
build-backend = "hatchling.build"